# Generated by Django 6.1.1 on 2026-09-20 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestures', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gesturedetection',
            options={'ordering': ['-detected_at']},
        ),
    ]
